"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { LayoutDashboard, Package, Route, Bike, Settings, Plus, ScanLine, Search, MapPin, Clock, CircleDollarSign, AlertTriangle, CheckCircle2, Navigation, MoreHorizontal, SlidersHorizontal, ChevronRight, Menu, X, RotateCw, Upload, Camera, MapPinned, Gauge, Users, Bell, Eye, Pencil, Trash2 } from "lucide-react";
import "leaflet/dist/leaflet.css";
import { currentPosition, geocode, reverseGeocode } from "../src/services/geocodingService";
import { calculateRoute } from "../src/services/routingService";
import { MAP_TILE_PROVIDERS, type MapTileProvider } from "../src/services/mapProviders";
import type { GeoPoint, RouteResult } from "../src/types";

type Status = "Aguardando" | "Pronta para sair" | "Em rota" | "Entregue" | "Problema";
type Delivery = { id:number; order:string; customer:string; phone:string; address:string; district:string; amount:number; deliveryFee:number; payment:string; priority:"Normal"|"Alta"|"Urgente"; status:Status; driver:string; time:string; latitude:number; longitude:number };

const STORE_POINT = { latitude: -13.0033, longitude: -38.4581 };
type LeafletMapHandle = { remove:()=>void; setView:(center:[number,number],zoom:number)=>unknown };

const initialDeliveries: Delivery[] = [
  {id:1,order:"#1847",customer:"Mariana Souza",phone:"(71) 98842-1093",address:"R. das Hortênsias, 224",district:"Pituba",amount:86.5,deliveryFee:8,payment:"Pix",priority:"Normal",status:"Pronta para sair",driver:"Rafael Santos",time:"12:30",latitude:-13.0014,longitude:-38.4589},
  {id:2,order:"#1848",customer:"Carlos Menezes",phone:"(71) 99211-4820",address:"Av. Oceânica, 1450",district:"Ondina",amount:124.9,deliveryFee:12,payment:"Cartão",priority:"Alta",status:"Aguardando",driver:"Não atribuído",time:"12:45",latitude:-13.0107,longitude:-38.5071},
  {id:3,order:"#1849",customer:"Aline Barreto",phone:"(71) 98733-6501",address:"R. Amazonas, 617",district:"Pituba",amount:52,deliveryFee:8,payment:"Dinheiro • troco R$ 100",priority:"Urgente",status:"Em rota",driver:"João Lima",time:"13:00",latitude:-12.9987,longitude:-38.4598},
  {id:4,order:"#1850",customer:"Paulo Almeida",phone:"(71) 98120-3377",address:"R. Leonor Calmon, 86",district:"Cidade Jardim",amount:76.2,deliveryFee:10,payment:"Pago",priority:"Normal",status:"Aguardando",driver:"Não atribuído",time:"13:15",latitude:-12.9964,longitude:-38.4802},
  {id:5,order:"#1851",customer:"Neide Carvalho",phone:"(71) 99671-0224",address:"Al. Benevento, 310",district:"Caminho das Árvores",amount:93.7,deliveryFee:12,payment:"Pix",priority:"Alta",status:"Pronta para sair",driver:"Rafael Santos",time:"13:20",latitude:-12.9818,longitude:-38.4659},
  {id:6,order:"#1843",customer:"Roberto Nascimento",phone:"(71) 99108-4452",address:"R. Pará, 42",district:"Pituba",amount:61.4,deliveryFee:8,payment:"Cartão",priority:"Normal",status:"Entregue",driver:"João Lima",time:"11:48",latitude:-13.0052,longitude:-38.4624},
  {id:7,order:"#1845",customer:"Lívia Rocha",phone:"(71) 98444-2098",address:"R. das Rosas, 181",district:"Pituba",amount:47.9,deliveryFee:9,payment:"Dinheiro",priority:"Normal",status:"Problema",driver:"Rafael Santos",time:"12:05",latitude:-13.0067,longitude:-38.4567},
  {id:8,order:"#1852",customer:"Sérgio Dantas",phone:"(71) 99903-7741",address:"Av. Paulo VI, 1280",district:"Itaigara",amount:109.8,deliveryFee:11,payment:"Pix",priority:"Normal",status:"Aguardando",driver:"Não atribuído",time:"13:40",latitude:-12.9894,longitude:-38.4634},
];

const nav = [
  ["Visão geral", LayoutDashboard], ["Entregas", Package], ["Planejar rota", Route], ["Motoboys", Bike], ["Configurações", Settings]
] as const;

export default function Home() {
  const [page,setPage]=useState("Visão geral"); const [mobile,setMobile]=useState(false); const [query,setQuery]=useState(""); const [deliveries,setDeliveries]=useState(initialDeliveries); const [modal,setModal]=useState<"new"|"ocr"|null>(null); const [toast,setToast]=useState(""); const [mapProvider,setMapProvider]=useState<MapTileProvider>("osm");
  const filtered=useMemo(()=>deliveries.filter(d=>(d.customer+d.order+d.address+d.phone).toLowerCase().includes(query.toLowerCase())),[deliveries,query]);
  const go=(p:string)=>{setPage(p);setMobile(false)};
  const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2600)};
  function saveDelivery(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setDeliveries(v=>[{id:Date.now(),order:String(f.get("order")||"#1853"),customer:String(f.get("customer")),phone:String(f.get("phone")),address:String(f.get("address")),district:String(f.get("district")),amount:Number(f.get("amount")),deliveryFee:Number(f.get("deliveryFee")),payment:String(f.get("payment")),priority:"Normal",status:"Aguardando",driver:"Não atribuído",time:"14:00",latitude:Number(f.get("latitude"))||STORE_POINT.latitude,longitude:Number(f.get("longitude"))||STORE_POINT.longitude},...v]);setModal(null);notify("Entrega cadastrada com taxa de "+money(Number(f.get("deliveryFee"))))}
  return <div className="app-shell">
    <aside className={mobile?"sidebar open":"sidebar"}>
      <div className="brand"><div className="brandmark"><Route size={24}/></div><div><b>Rota Certa</b><span>Gestão de entregas</span></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div>
      <nav>{nav.map(([label,Icon])=><button key={label} onClick={()=>go(label)} className={page===label?"active":""}><Icon size={20}/><span>{label}</span>{label==="Entregas"&&<em>5</em>}</button>)}</nav>
      <div className="ops-card"><span className="live-dot"/> <b>Operação ativa</b><small>Loja aberta até 22h</small><div><span>Hoje</span><strong>8 entregas</strong></div></div>
      <div className="user"><div className="avatar">AS</div><div><b>André Silva</b><span>Administrador</span></div><MoreHorizontal size={20}/></div>
    </aside>
    <main>
      <header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{page}</h1><p>{subtitle(page)}</p></div><div className="head-actions"><span className="demo"><span/> Modo demonstração</span><button className="icon-btn"><Bell size={19}/><i/></button><button className="primary" onClick={()=>setModal("new")}><Plus size={19}/> Nova entrega</button></div></header>
      {page==="Visão geral"&&<Dashboard deliveries={deliveries} go={go} setModal={setModal} mapProvider={mapProvider}/>} 
      {page==="Entregas"&&<Deliveries data={filtered} query={query} setQuery={setQuery} remove={(id)=>{setDeliveries(v=>v.filter(d=>d.id!==id));notify("Entrega excluída")}}/>}
      {page==="Planejar rota"&&<RoutePlanner deliveries={deliveries} notify={notify} mapProvider={mapProvider}/>} 
      {page==="Motoboys"&&<Drivers/>}
      {page==="Configurações"&&<Config notify={notify} mapProvider={mapProvider} setMapProvider={setMapProvider}/>} 
    </main>
    <div className="bottom-nav">{nav.slice(0,4).map(([l,I])=><button key={l} onClick={()=>go(l)} className={page===l?"active":""}><I/><span>{l.replace("Visão geral","Início").replace("Planejar rota","Rotas")}</span></button>)}</div>
    {modal==="new"&&<NewDelivery close={()=>setModal(null)} save={saveDelivery}/>} {modal==="ocr"&&<OCR close={()=>setModal(null)} done={()=>{setModal(null);setModal("new");notify("Comanda lida. Confira os campos destacados")}}/>}
    {toast&&<div className="toast"><CheckCircle2/>{toast}</div>}
  </div>
}

function subtitle(p:string){return ({"Visão geral":"Acompanhe a operação de hoje, 4 de agosto","Entregas":"Consulte e organize todos os pedidos","Planejar rota":"Organize as paradas e reduza o caminho","Motoboys":"Equipe e desempenho da operação","Configurações":"Estabelecimento e integrações"} as Record<string,string>)[p]}

function Dashboard({deliveries,go,setModal,mapProvider}:{deliveries:Delivery[];go:(p:string)=>void;setModal:(v:"ocr")=>void;mapProvider:MapTileProvider}){
 const cards=[["Aguardando saída","5","+2 desde 12h",Package,"teal"],["Em rota","1","João Lima",Bike,"blue"],["Concluídas hoje","12","86% no prazo",CheckCircle2,"green"],["Com problema","1","Requer atenção",AlertTriangle,"orange"]] as const;
 const listedFees=deliveries.reduce((sum,d)=>sum+d.deliveryFee,0);
 return <div className="content"><section className="quick"><button onClick={()=>go("Planejar rota")}><span className="qicon route"><Route/></span><div><b>Montar rota</b><small>5 entregas aguardando</small></div><ChevronRight/></button><button onClick={()=>setModal("ocr")}><span className="qicon scan"><ScanLine/></span><div><b>Ler comanda</b><small>Foto ou imagem da galeria</small></div><ChevronRight/></button><button onClick={()=>go("Entregas")}><span className="qicon pin"><MapPin/></span><div><b>Revisar endereços</b><small>1 endereço incompleto</small></div><ChevronRight/></button></section>
 <section className="metrics">{cards.map(([t,n,s,I,c])=><article key={t}><div className={"metric-icon "+c}><I/></div><div><span>{t}</span><strong>{n}</strong><small>{s}</small></div></article>)}</section>
 <section className="workspace"><div className="map-card"><div className="card-title"><div><h2>Mapa da operação</h2><p>Mapa gratuito com localização por GPS</p></div><button><MapPinned size={18}/> {MAP_TILE_PROVIDERS[mapProvider].name}</button></div><FreeMap deliveries={deliveries} mapProvider={mapProvider}/><div className="map-legend"><span><i className="dot waiting"/>Aguardando 5</span><span><i className="dot transit"/>Em rota 1</span><span><i className="dot done"/>Entregues 12</span></div></div>
 <div className="next-card"><div className="card-title"><div><h2>Próximas entregas</h2><p>Ordenadas pelo horário máximo</p></div><button className="text-btn" onClick={()=>go("Entregas")}>Ver todas</button></div>{deliveries.slice(0,4).map((d,i)=><div className="next-row" key={d.id}><div className={"timebox "+(i===0?"urgent":"")}><b>{d.time}</b><span>{i===0?"em 18 min":"hoje"}</span></div><div><b>{d.customer}</b><span><MapPin/> {d.district} · {d.address}</span><small>{d.order} · {d.payment}</small></div><StatusBadge status={d.status}/></div>)}</div></section>
 <section className="earnings"><div className="earnings-title"><span className="sum-icon"><CircleDollarSign/></span><div><h2>Faturamento das entregas</h2><p>Somente taxas de entrega — não inclui o valor dos pedidos</p></div></div><div><span>Já realizado hoje</span><b>R$ 124,00</b><small>12 entregas concluídas</small></div><div><span>Em aberto nesta lista</span><b>{money(listedFees-8)}</b><small>7 entregas</small></div><div className="earnings-total"><span>Total previsto</span><b>{money(124+listedFees-8)}</b><small>Concluídas + pendentes</small></div></section>
 <section className="summary"><article><div className="sum-icon"><Gauge/></div><div><span>Distância planejada</span><b>24,8 km</b><small>3 rotas ativas</small></div></article><article><div className="sum-icon"><Clock/></div><div><span>Tempo médio</span><b>28 min</b><small className="positive">↓ 4 min esta semana</small></div></article><article><div className="sum-icon"><Users/></div><div><span>Motoboys ativos</span><b>2 de 3</b><small>1 fora de turno</small></div></article><article><div className="sum-icon"><CircleDollarSign/></div><div><span>Valor dos pedidos</span><b>R$ 1.284,60</b><small>Separado das taxas</small></div></article></section></div>
}

function FreeMap({deliveries,mapProvider,route}:{deliveries:Delivery[];mapProvider:MapTileProvider;route?:RouteResult|null}){
  const element=useRef<HTMLDivElement|null>(null); const map=useRef<LeafletMapHandle|null>(null); const [gpsMessage,setGpsMessage]=useState("");
  useEffect(()=>{let active=true; void import("leaflet").then(L=>{if(!active||!element.current)return; map.current?.remove(); const instance=L.map(element.current,{zoomControl:true}).setView([STORE_POINT.latitude,STORE_POINT.longitude],13); map.current=instance; const tile=MAP_TILE_PROVIDERS[mapProvider]; L.tileLayer(tile.url,{attribution:tile.attribution,maxZoom:tile.maxZoom}).addTo(instance); const bounds:Array<[number,number]>=[]; L.circleMarker([STORE_POINT.latitude,STORE_POINT.longitude],{radius:9,color:"#fff",weight:3,fillColor:"#0b5c54",fillOpacity:1}).bindPopup("Ponto de saída").addTo(instance); bounds.push([STORE_POINT.latitude,STORE_POINT.longitude]); deliveries.forEach((delivery,index)=>{const color=delivery.status==="Entregue"?"#459664":delivery.status==="Em rota"?"#3577a9":"#ed7d38"; L.circleMarker([delivery.latitude,delivery.longitude],{radius:9,color:"#fff",weight:3,fillColor:color,fillOpacity:1}).bindTooltip(String(index+1),{permanent:true,direction:"center",className:"route-number"}).bindPopup(`<strong>${delivery.customer}</strong><br>${delivery.address}<br>${delivery.district}`).addTo(instance); bounds.push([delivery.latitude,delivery.longitude]);}); if(route?.geometry.length){const line=route.geometry.map(point=>[point.latitude,point.longitude] as [number,number]); L.polyline(line,{color:"#087b6e",weight:5,opacity:.88}).addTo(instance); bounds.push(...line);} if(bounds.length>1)instance.fitBounds(L.latLngBounds(bounds),{padding:[28,28],maxZoom:15}); setTimeout(()=>instance.invalidateSize(),50);}); return()=>{active=false;map.current?.remove();map.current=null}},[deliveries,mapProvider,route]);
  async function locate(){setGpsMessage("Localizando…");try{const point=await currentPosition();map.current?.setView([point.latitude,point.longitude],16);const L=await import("leaflet");if(map.current)L.circleMarker([point.latitude,point.longitude],{radius:10,color:"#fff",weight:3,fillColor:"#2563eb",fillOpacity:1}).bindPopup("Sua localização").addTo(map.current).openPopup();setGpsMessage("Localização encontrada")}catch(error){setGpsMessage(error instanceof Error?error.message:"GPS indisponível")}}
  return <div className="live-map-wrap"><div ref={element} className="live-map"/><div className="map-live-controls"><button type="button" onClick={locate}><Navigation size={15}/> Minha localização</button>{gpsMessage&&<span>{gpsMessage}</span>}</div></div>
}

function Deliveries({data,query,setQuery,remove}:{data:Delivery[];query:string;setQuery:(s:string)=>void;remove:(id:number)=>void}){const fees=data.reduce((s,d)=>s+d.deliveryFee,0);return <div className="content"><div className="list-finance"><div><span>Taxas desta lista</span><b>{money(fees)}</b></div><div><span>Já concluído</span><b>{money(data.filter(d=>d.status==="Entregue").reduce((s,d)=>s+d.deliveryFee,0))}</b></div><div><span>Valor dos pedidos</span><b>{money(data.reduce((s,d)=>s+d.amount,0))}</b></div></div><div className="toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente, telefone, endereço ou pedido"/></label><button><SlidersHorizontal/> Filtros <em>2</em></button><select><option>Todos os status</option><option>Aguardando</option><option>Em rota</option></select><select><option>Hoje, 4 ago.</option></select></div><div className="table-card"><div className="table-head"><b>{data.length} entregas</b><span>Atualizado agora</span></div><div className="delivery-table"><div className="tr th"><span>Pedido / Cliente</span><span>Endereço</span><span>Pedido / Taxa</span><span>Prioridade</span><span>Motoboy</span><span>Status</span><span/></div>{data.map(d=><div className="tr" key={d.id}><span><b>{d.order} · {d.customer}</b><small>{d.phone} · {d.time}</small></span><span><b>{d.district}</b><small>{d.address}</small></span><span><b>{money(d.amount)}</b><small className="fee-value">Taxa: {money(d.deliveryFee)}</small></span><span><Priority p={d.priority}/></span><span><b>{d.driver}</b></span><span><StatusBadge status={d.status}/></span><span className="row-actions"><button title="Visualizar"><Eye/></button><button title="Editar"><Pencil/></button><button title="Excluir" onClick={()=>remove(d.id)}><Trash2/></button></span></div>)}</div></div></div>}

function RoutePlanner({deliveries,notify,mapProvider}:{deliveries:Delivery[];notify:(s:string)=>void;mapProvider:MapTileProvider}){
  const [result,setResult]=useState<RouteResult|null>(null); const [loading,setLoading]=useState(false); const [returnToStart,setReturnToStart]=useState(true); const [expectedReturn,setExpectedReturn]=useState("—"); const selected=deliveries.filter(d=>d.status!=="Entregue"&&d.status!=="Problema").slice(0,5);
  async function calculate(){setLoading(true);try{const route=await calculateRoute([STORE_POINT,...selected.map(d=>({latitude:d.latitude,longitude:d.longitude}))],returnToStart);setResult(route);const returnMinutes=(13*60+30+Math.ceil(route.durationSeconds/60))%(24*60);setExpectedReturn(`${String(Math.floor(returnMinutes/60)).padStart(2,"0")}:${String(returnMinutes%60).padStart(2,"0")}`);notify(`Rota calculada gratuitamente por ${providerName(route.provider)}`)}catch(error){notify(error instanceof Error?error.message:"Não foi possível calcular a rota")}finally{setLoading(false)}}
  const minutes=result?Math.round(result.durationSeconds/60):0;
  return <div className="route-page"><div className="route-panel"><div className="route-config"><label>Ponto de saída<select><option>Mercadinho Boa Praça — Pituba</option><option>Usar minha localização atual</option></select></label><div className="inline"><label>Motoboy<select><option>Rafael Santos</option><option>João Lima</option></select></label><label>Saída<input type="time" defaultValue="13:30"/></label></div><label className="check"><input type="checkbox" checked={returnToStart} onChange={event=>setReturnToStart(event.target.checked)}/> Retornar ao estabelecimento</label></div><div className="stop-title"><div><b>Paradas selecionadas</b><span>{selected.length} de 5</span></div><button>Selecionar entregas</button></div><div className="stops">{selected.map((d,i)=><div className="stop" key={d.id}><i>⋮⋮</i><strong>{result?i+1:"·"}</strong><div><b>{d.customer}</b><span>{d.district} · {d.address}</span><small>{d.order} · até {d.time}</small></div><Priority p={d.priority}/><button><X/></button></div>)}</div><div className="route-actions"><button className="primary wide" disabled={loading} onClick={calculate}><Route/> {loading?"Calculando em serviços gratuitos…":result?"Recalcular rota":"Calcular melhor rota"}</button>{result&&<small>Rota viária: {providerName(result.provider)} · fallback automático ativo</small>}</div></div><div className="route-map"><div className="route-summary"><div><span>Distância total</span><b>{result?(result.distanceMeters/1000).toLocaleString("pt-BR",{maximumFractionDigits:1})+" km":"—"}</b></div><div><span>Tempo estimado</span><b>{result?(minutes>=60?`${Math.floor(minutes/60)}h ${minutes%60}min`:`${minutes} min`):"—"}</b></div><div><span>Paradas</span><b>{result?selected.length:"—"}</b></div><div><span>Retorno previsto</span><b>{expectedReturn}</b></div>{result&&<button className="primary" onClick={()=>notify("Planejamento salvo")}>Salvar planejamento</button>}</div><FreeMap deliveries={result?selected:[]} mapProvider={mapProvider} route={result}/>{!result&&!loading&&<div className="map-empty"><Route/><b>A rota aparecerá aqui</b><span>OSRM, Valhalla e fallback local estão disponíveis sem cobrança.</span></div>}</div></div>
}

function providerName(provider:RouteResult["provider"]){return ({osrm:"OSRM",valhalla:"Valhalla",openrouteservice:"OpenRouteService",graphhopper:"GraphHopper",local:"cálculo local"} as const)[provider]}

function Drivers(){return <div className="content"><div className="section-head"><div><h2>Equipe de entrega</h2><p>2 motoboys ativos agora</p></div><button className="primary"><Plus/> Cadastrar motoboy</button></div><div className="driver-grid">{[["RS","Rafael Santos","Honda CG 160","PLQ-4A82","6 entregas","R$ 56,00 em taxas"],["JL","João Lima","Yamaha Factor 150","RDN-8B21","12 entregas","R$ 124,00 em taxas"],["MC","Márcio Costa","Honda Pop 110i","—","8 entregas","R$ 82,00 em taxas"]].map((d,i)=><article key={d[1]}><div className="driver-top"><div className="driver-avatar">{d[0]}</div><div><b>{d[1]}</b><span>(71) 99{i+2}40-18{i}2</span></div><MoreHorizontal/></div><div className="vehicle"><Bike/><div><span>{d[2]}</span><b>{d[3]}</b></div></div><div className="driver-earnings"><span>Fez hoje</span><b>{d[5]}</b></div><div className="driver-foot"><StatusBadge status={i===0?"Em rota":i===1?"Pronta para sair":"Aguardando"}/><span>{d[4]}</span></div></article>)}</div></div>}

function Config({notify,mapProvider,setMapProvider}:{notify:(s:string)=>void;mapProvider:MapTileProvider;setMapProvider:(provider:MapTileProvider)=>void}){const integrations=[["OpenStreetMap / CARTO / OpenTopoMap","Mapas sem chave e sem cobrança"],["Nominatim + Photon","Busca e localização de endereços"],["OSRM + Valhalla","Roteirização viária gratuita"],["GPS do aparelho","Localização atual com permissão"],["Cálculo local","Fallback disponível sem internet de rotas"]];return <div className="content config"><section><h2>Dados do estabelecimento</h2><p>Usados como ponto padrão de saída das rotas.</p><div className="form-grid"><label>Nome do estabelecimento<input defaultValue="Mercadinho Boa Praça"/></label><label>Telefone<input defaultValue="(71) 3345-8820"/></label><label className="full">Endereço principal<input defaultValue="Rua das Acácias, 350 — Pituba, Salvador — BA"/></label><label>Mapa gratuito<select value={mapProvider} onChange={event=>setMapProvider(event.target.value as MapTileProvider)}>{Object.entries(MAP_TILE_PROVIDERS).map(([id,provider])=><option key={id} value={id}>{provider.name}</option>)}</select></label><label>Limite por rota<select><option>10 entregas</option></select></label></div><button className="primary" onClick={()=>notify("Configurações salvas")}>Salvar alterações</button></section><section><h2>APIs gratuitas</h2><p>Serviços ativados com fallback automático.</p>{integrations.map(x=><div className="integration" key={x[0]}><div className="ok"><CheckCircle2/></div><div><b>{x[0]}</b><span>{x[1]}</span></div><span className="free-badge">GRÁTIS</span></div>)}</section></div>}

function NewDelivery({close,save}:{close:()=>void;save:(e:React.FormEvent<HTMLFormElement>)=>void}){
  const form=useRef<HTMLFormElement|null>(null); const [location,setLocation]=useState<GeoPoint|null>(null); const [locationText,setLocationText]=useState("Use a busca gratuita ou o GPS do aparelho."); const [locating,setLocating]=useState(false);
  async function locateAddress(){if(!form.current)return;const data=new FormData(form.current);const address=[data.get("address"),data.get("district"),data.get("city"),"BA","Brasil"].filter(Boolean).join(", ");setLocating(true);setLocationText("Buscando endereço…");try{const result=await geocode(address);if(!result){setLocationText("Endereço não encontrado. Complete rua, número e bairro.");return}setLocation(result);setLocationText(`${result.displayName} · ${result.provider||"serviço gratuito"}`)}catch(error){setLocationText(error instanceof Error?error.message:"Busca indisponível")}finally{setLocating(false)}}
  async function useGps(){setLocating(true);setLocationText("Obtendo localização do aparelho…");try{const point=await currentPosition();setLocation(point);const address=await reverseGeocode(point);setLocationText(address?.displayName||"Localização GPS encontrada")}catch(error){setLocationText(error instanceof Error?error.message:"GPS indisponível")}finally{setLocating(false)}}
  return <div className="overlay"><div className="modal large"><div className="modal-head"><div><h2>Nova entrega</h2><p>Cadastre o pedido e localize gratuitamente no mapa.</p></div><button onClick={close}><X/></button></div><form ref={form} onSubmit={save}><input type="hidden" name="latitude" value={location?.latitude||""}/><input type="hidden" name="longitude" value={location?.longitude||""}/><div className="form-grid"><label>Número do pedido<input name="order" defaultValue="#1853" required/></label><label>Nome do cliente<input name="customer" placeholder="Nome completo" required/></label><label>Telefone<input name="phone" placeholder="(71) 99999-9999" required/></label><label>CEP<input name="postalCode" placeholder="00000-000"/></label><label className="full">Rua e número<input name="address" placeholder="Ex.: Rua das Acácias, 120" required/></label><label>Bairro<input name="district" placeholder="Bairro" required/></label><label>Cidade<input name="city" defaultValue="Salvador"/></label><label>Valor do pedido<input name="amount" type="number" step="0.01" placeholder="R$ 0,00" required/></label><label>Valor da entrega<input name="deliveryFee" type="number" step="0.01" placeholder="R$ 0,00" required/><small className="field-help">Taxa que será somada ao faturamento das entregas</small></label><label>Forma de pagamento<select name="payment"><option>Pix</option><option>Dinheiro</option><option>Cartão</option><option>Pago</option></select></label><label className="full">Observações<textarea placeholder="Ponto de referência, instruções ou troco"/></label></div><div className="locate"><MapPin/><div><b>Localização do endereço</b><span>{locationText}</span></div><div className="locate-actions"><button type="button" disabled={locating} onClick={locateAddress}>Buscar endereço</button><button type="button" disabled={locating} onClick={useGps}><Navigation size={14}/> Usar GPS</button></div></div><div className="modal-actions"><button type="button" onClick={close}>Cancelar</button><button className="primary" type="submit">Confirmar e cadastrar entrega</button></div></form></div></div>
}

function OCR({close,done}:{close:()=>void;done:()=>void}){const [image,setImage]=useState(false);const [progress,setProgress]=useState(0);function process(){setProgress(18);let n=18;const id=setInterval(()=>{n+=17;setProgress(Math.min(n,100));if(n>=100){clearInterval(id);setTimeout(done,300)}},280)}return <div className="overlay"><div className="modal ocr-modal"><div className="modal-head"><div><h2>Ler comanda</h2><p>A imagem é processada somente neste aparelho.</p></div><button onClick={close}><X/></button></div>{!image?<div className="dropzone"><div><ScanLine/></div><b>Fotografe ou escolha uma comanda</b><span>Use uma foto nítida, bem iluminada e sem inclinação.</span><button className="primary" onClick={()=>setImage(true)}><Camera/> Tirar foto</button><button onClick={()=>setImage(true)}><Upload/> Escolher da galeria</button></div>:<><div className="receipt-preview"><div className="paper"><b>MERCADINHO BOA PRAÇA</b><span>PEDIDO #1853</span><hr/><p>Cliente: Fernanda Ribeiro</p><p>Tel: (71) 99921-8864</p><p>Endereço: Rua Ceará, 481</p><p>Pituba - Salvador/BA</p><hr/><strong>TOTAL R$ 78,40</strong><p>Pagamento: PIX</p></div><button title="Girar"><RotateCw/></button></div>{progress>0?<div className="progress"><div><span style={{width:progress+"%"}}/></div><b>Lendo comanda… {progress}%</b><small>Reconhecendo texto em português</small></div>:<button className="primary wide" onClick={process}><ScanLine/> Iniciar leitura</button>}</>}</div></div>}

function StatusBadge({status}:{status:Status}){return <span className={"status "+status.toLowerCase().replaceAll(" ","-")}>{status}</span>}
function Priority({p}:{p:Delivery["priority"]}){return <span className={"priority "+p.toLowerCase()}>{p}</span>}
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
