"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { LayoutDashboard, Package, Route, Bike, Settings, Plus, ScanLine, Search, MapPin, Clock, CircleDollarSign, AlertTriangle, CheckCircle2, Navigation, MoreHorizontal, SlidersHorizontal, ChevronRight, Menu, X, RotateCw, Upload, Camera, MapPinned, Gauge, Users, Bell, Eye, Pencil, Trash2, UserRound } from "lucide-react";
import "leaflet/dist/leaflet.css";
import { currentPosition, geocode, reverseGeocode } from "../src/services/geocodingService";
import { calculateRoute } from "../src/services/routingService";
import { MAP_TILE_PROVIDERS, type MapTileProvider } from "../src/services/mapProviders";
import type { GeoPoint, RouteResult } from "../src/types";
import { EmptyState } from "../src/components/EmptyState";

type Status = "Aguardando" | "Pronta para sair" | "Em rota" | "Entregue" | "Problema";
type Delivery = { id:number; order:string; customer:string; phone:string; address:string; district:string; amount:number; deliveryFee:number; payment:string; priority:"Normal"|"Alta"|"Urgente"; status:Status; driver:string; time:string; latitude:number; longitude:number };

const STORE_KEY="rotacerta_store";
const DELIV_KEY="rotacerta_deliveries";
type StoreCfg={name:string;phone:string;address:string;latitude:number;longitude:number};
function loadStore():StoreCfg{try{const raw=typeof localStorage!=="undefined"?localStorage.getItem(STORE_KEY):null;const s=raw?JSON.parse(raw):null;if(s&&typeof s.latitude==="number")return s;}catch{} return {name:"",phone:"",address:"",latitude:-13.0033,longitude:-38.4581};}
let STORE_POINT:StoreCfg = loadStore();
function saveStore(cfg:StoreCfg){STORE_POINT=cfg;try{localStorage.setItem(STORE_KEY,JSON.stringify(cfg));}catch{}}
type LeafletMapHandle = { remove:()=>void; setView:(center:[number,number],zoom:number)=>unknown };

const initialDeliveries: Delivery[] = [];

const nav = [
  ["Visão geral", LayoutDashboard], ["Entregas", Package], ["Mapa", MapPinned], ["Planejar rota", Route], ["Motoboys", Bike], ["Configurações", Settings]
] as const;

const mobileNav = [
  ["Visão geral", "Início", LayoutDashboard],
  ["Entregas", "Entregas", Package],
  ["Mapa", "Mapa", MapPinned],
  ["Planejar rota", "Rotas", Route],
  ["Configurações", "Perfil", UserRound],
] as const;

export default function Home() {
  const [page,setPage]=useState("Visão geral"); const [mobile,setMobile]=useState(false); const [query,setQuery]=useState(""); const [deliveries,setDeliveries]=useState<Delivery[]>(()=>{try{const raw=typeof localStorage!=="undefined"?localStorage.getItem(DELIV_KEY):null;const s=raw?JSON.parse(raw):null;return Array.isArray(s)?s:initialDeliveries;}catch{return initialDeliveries;}});const [ocrData,setOcrData]=useState<Record<string,string>|null>(null); const [modal,setModal]=useState<"new"|"ocr"|null>(null); const [toast,setToast]=useState(""); const [mapProvider,setMapProvider]=useState<MapTileProvider>("osm");
  const filtered=useMemo(()=>deliveries.filter(d=>(d.customer+d.order+d.address+d.phone).toLowerCase().includes(query.toLowerCase())),[deliveries,query]);
  useEffect(()=>{try{localStorage.setItem(DELIV_KEY,JSON.stringify(deliveries));}catch{}},[deliveries]);const go=(p:string)=>{setPage(p);setMobile(false)};
  const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2600)};
  function saveDelivery(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setDeliveries(v=>[{id:Date.now(),order:String(f.get("order")||"#1853"),customer:String(f.get("customer")),phone:String(f.get("phone")),address:String(f.get("address")),district:String(f.get("district")),amount:Number(f.get("amount")),deliveryFee:Number(f.get("deliveryFee")),payment:String(f.get("payment")),priority:"Normal",status:"Aguardando",driver:"Não atribuído",time:"14:00",latitude:Number(f.get("latitude"))||STORE_POINT.latitude,longitude:Number(f.get("longitude"))||STORE_POINT.longitude},...v]);setModal(null);notify("Entrega cadastrada com taxa de "+money(Number(f.get("deliveryFee"))))}
  return <div className="app-shell">
    <aside className={mobile?"sidebar open":"sidebar"}>
      <div className="brand"><div className="brandmark"><Route size={24}/></div><div><b>Rota Certa</b><span>Gestão de entregas</span></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div>
      <nav>{nav.map(([label,Icon])=><button key={label} onClick={()=>go(label)} className={page===label?"active":""}><Icon size={20}/><span>{label}</span>{label==="Entregas"&&<em>5</em>}</button>)}</nav>
      <div className="ops-card"><span className="live-dot"/> <b>Operação ativa</b><small>Loja aberta até 22h</small><div><span>Hoje</span><strong>{deliveries.length} entrega(s)</strong></div></div>
      <div className="user"><div className="avatar">AS</div><div><b>André Silva</b><span>Administrador</span></div><MoreHorizontal size={20}/></div>
    </aside>
    <main>
      <header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{page}</h1><p>{subtitle(page)}</p></div><div className="head-actions"><button className="icon-btn"><Bell size={19}/><i/></button><button className="primary" onClick={()=>setModal("new")}><Plus size={19}/> Nova entrega</button></div></header>
      {page==="Visão geral"&&<Dashboard deliveries={deliveries} go={go} setModal={setModal} mapProvider={mapProvider}/>} 
      {page==="Entregas"&&<Deliveries data={filtered} query={query} setQuery={setQuery} remove={(id)=>{setDeliveries(v=>v.filter(d=>d.id!==id));notify("Entrega excluída")}}/>}
      {page==="Mapa"&&<MapOverview deliveries={deliveries} mapProvider={mapProvider} go={go}/>}
      {page==="Planejar rota"&&<RoutePlanner deliveries={deliveries} notify={notify} mapProvider={mapProvider}/>} 
      {page==="Motoboys"&&<Drivers/>}
      {page==="Configurações"&&<Config notify={notify} mapProvider={mapProvider} setMapProvider={setMapProvider}/>} 
    </main>
    <div className="bottom-nav" aria-label="Navegação principal">{mobileNav.map(([target,label,Icon])=><button key={target} onClick={()=>go(target)} className={page===target?"active":""} aria-current={page===target?"page":undefined}><Icon/><span>{label}</span></button>)}</div>
    {modal==="new"&&<NewDelivery close={()=>{setModal(null);setOcrData(null);}} save={saveDelivery} prefill={ocrData}/>} {modal==="ocr"&&<OCR close={()=>setModal(null)} done={(fields:Record<string,string>)=>{setOcrData(fields);setModal("new");notify("Comanda lida. Confira e ajuste os campos antes de salvar.")}}/>}
    {toast&&<div className="toast"><CheckCircle2/>{toast}</div>}
  </div>
}

function subtitle(p:string){return ({"Visão geral":"Acompanhe a operação de hoje","Entregas":"Consulte e organize todos os pedidos","Mapa":"Veja entregas e rotas próximas","Planejar rota":"Organize as paradas e reduza o caminho","Motoboys":"Equipe e desempenho da operação","Configurações":"Estabelecimento e integrações"} as Record<string,string>)[p]}

function Dashboard({deliveries,go,setModal,mapProvider}:{deliveries:Delivery[];go:(p:string)=>void;setModal:(v:"new"|"ocr")=>void;mapProvider:MapTileProvider}){
 const aguardando=deliveries.filter(d=>d.status==="Aguardando"||d.status==="Pronta para sair").length;
 const emRota=deliveries.filter(d=>d.status==="Em rota").length;
 const entregues=deliveries.filter(d=>d.status==="Entregue").length;
 const problema=deliveries.filter(d=>d.status==="Problema").length;
 const feesAberto=deliveries.filter(d=>d.status!=="Entregue").reduce((sum,d)=>sum+(d.deliveryFee||0),0);
 const feesConcluido=deliveries.filter(d=>d.status==="Entregue").reduce((sum,d)=>sum+(d.deliveryFee||0),0);
 const cards=[["Aguardando saida",String(aguardando),"pendentes",Package,"teal"],["Em rota",String(emRota),"em entrega",Bike,"blue"],["Concluidas hoje",String(entregues),"finalizadas",CheckCircle2,"green"],["Com problema",String(problema),"requer atencao",AlertTriangle,"orange"]] as const;
 return <div className="content"><section className="quick"><button className="quick-primary" onClick={()=>setModal("new")}><span className="qicon add"><Plus/></span><div><b>Nova entrega</b><small>Cadastro rápido</small></div><ChevronRight/></button><button onClick={()=>setModal("ocr")}><span className="qicon scan"><ScanLine/></span><div><b>Ler comanda</b><small>Câmera ou galeria</small></div><ChevronRight/></button><button onClick={()=>go("Planejar rota")}><span className="qicon route"><Route/></span><div><b>Montar rota</b><small>{aguardando} aguardando</small></div><ChevronRight/></button></section>
 <section className="metrics">{cards.map(([t,n,sub,I,c])=><article key={t}><div className={"metric-icon "+c}><I/></div><div><span>{t}</span><strong>{n}</strong><small>{sub}</small></div></article>)}</section>
 <section className="workspace"><div className="map-card"><div className="card-title"><div><h2>Mapa da operacao</h2><p>Mapa gratuito com localizacao por GPS</p></div><button><MapPinned size={18}/> {MAP_TILE_PROVIDERS[mapProvider].name}</button></div><FreeMap deliveries={deliveries} mapProvider={mapProvider}/><div className="map-legend"><span><i className="dot waiting"/>Aguardando {aguardando}</span><span><i className="dot transit"/>Em rota {emRota}</span><span><i className="dot done"/>Entregues {entregues}</span></div></div>
 <div className="next-card"><div className="card-title"><div><h2>Proximas entregas</h2><p>Ordenadas pela lista</p></div><button className="text-btn" onClick={()=>go("Entregas")}>Ver todas</button></div>{deliveries.length===0?<div style={{padding:"26px",textAlign:"center",color:"#6c7a77",fontSize:"12px"}}>Nenhuma entrega ainda. Use <b>Ler comanda</b> ou <b>Nova entrega</b>.</div>:deliveries.slice(0,5).map((d)=><div className="next-row" key={d.id}><div className="timebox"><b>{d.time}</b><span>hoje</span></div><div><b>{d.customer}</b><span><MapPin/> {d.district} · {d.address}</span><small>{d.order} · {d.payment}</small></div><StatusBadge status={d.status}/></div>)}</div></section>
 <section className="earnings"><div className="earnings-title"><span className="sum-icon"><CircleDollarSign/></span><div><h2>Faturamento das entregas</h2><p>Somente taxas de entrega - nao inclui o valor dos pedidos</p></div></div><div><span>Ja realizado hoje</span><b>{money(feesConcluido)}</b><small>{entregues} entrega(s) concluida(s)</small></div><div><span>Em aberto nesta lista</span><b>{money(feesAberto)}</b><small>{aguardando+emRota} entrega(s)</small></div><div className="earnings-total"><span>Total previsto</span><b>{money(feesConcluido+feesAberto)}</b><small>Concluidas + pendentes</small></div></section>
 <section className="summary"><article><div className="sum-icon"><Gauge/></div><div><span>Total de entregas</span><b>{deliveries.length}</b><small>na lista</small></div></article><article><div className="sum-icon"><Clock/></div><div><span>Aguardando</span><b>{aguardando}</b><small>para sair</small></div></article><article><div className="sum-icon"><Users/></div><div><span>Concluidas</span><b>{entregues}</b><small>hoje</small></div></article><article><div className="sum-icon"><CircleDollarSign/></div><div><span>Valor dos pedidos</span><b>{money(deliveries.reduce((sum,d)=>sum+(d.amount||0),0))}</b><small>separado das taxas</small></div></article></section></div>;
}

function FreeMap({deliveries,mapProvider,route}:{deliveries:Delivery[];mapProvider:MapTileProvider;route?:RouteResult|null}){
  const element=useRef<HTMLDivElement|null>(null); const map=useRef<LeafletMapHandle|null>(null); const [gpsMessage,setGpsMessage]=useState("");
  useEffect(()=>{let active=true; void import("leaflet").then(L=>{if(!active||!element.current)return; map.current?.remove(); const instance=L.map(element.current,{zoomControl:true}).setView([STORE_POINT.latitude,STORE_POINT.longitude],13); map.current=instance; const tile=MAP_TILE_PROVIDERS[mapProvider]; L.tileLayer(tile.url,{attribution:tile.attribution,maxZoom:tile.maxZoom}).addTo(instance); const bounds:Array<[number,number]>=[]; L.circleMarker([STORE_POINT.latitude,STORE_POINT.longitude],{radius:9,color:"#fff",weight:3,fillColor:"#0b5c54",fillOpacity:1}).bindPopup("Ponto de saída").addTo(instance); bounds.push([STORE_POINT.latitude,STORE_POINT.longitude]); deliveries.forEach((delivery,index)=>{const color=delivery.status==="Entregue"?"#459664":delivery.status==="Em rota"?"#3577a9":"#ed7d38"; L.circleMarker([delivery.latitude,delivery.longitude],{radius:9,color:"#fff",weight:3,fillColor:color,fillOpacity:1}).bindTooltip(String(index+1),{permanent:true,direction:"center",className:"route-number"}).bindPopup(`<strong>${delivery.customer}</strong><br>${delivery.address}<br>${delivery.district}`).addTo(instance); bounds.push([delivery.latitude,delivery.longitude]);}); if(route?.geometry.length){const line=route.geometry.map(point=>[point.latitude,point.longitude] as [number,number]); L.polyline(line,{color:"#087b6e",weight:5,opacity:.88}).addTo(instance); bounds.push(...line);} if(bounds.length>1)instance.fitBounds(L.latLngBounds(bounds),{padding:[28,28],maxZoom:15}); setTimeout(()=>instance.invalidateSize(),50);}); return()=>{active=false;map.current?.remove();map.current=null}},[deliveries,mapProvider,route]);
  async function locate(){setGpsMessage("Localizando…");try{const point=await currentPosition();map.current?.setView([point.latitude,point.longitude],16);const L=await import("leaflet");if(map.current)L.circleMarker([point.latitude,point.longitude],{radius:10,color:"#fff",weight:3,fillColor:"#2563eb",fillOpacity:1}).bindPopup("Sua localização").addTo(map.current).openPopup();setGpsMessage("Localização encontrada")}catch(error){setGpsMessage(error instanceof Error?error.message:"GPS indisponível")}}
  return <div className="live-map-wrap"><div ref={element} className="live-map"/><div className="map-live-controls"><button type="button" onClick={locate}><Navigation size={15}/> Minha localização</button>{gpsMessage&&<span>{gpsMessage}</span>}</div></div>
}

function MapOverview({deliveries,mapProvider,go}:{deliveries:Delivery[];mapProvider:MapTileProvider;go:(page:string)=>void}){
  const visible=deliveries.filter(delivery=>delivery.status!=="Entregue");
  return <div className="content map-overview"><section className="map-overview-head"><div><h2>Mapa da operação</h2><p>{visible.length} entrega(s) pendente(s) ou em rota</p></div><button className="primary" type="button" onClick={()=>go("Planejar rota")}><Route/> Montar rota</button></section>{visible.length?<div className="map-overview-card"><FreeMap deliveries={visible} mapProvider={mapProvider}/><div className="map-overview-list">{visible.slice(0,4).map((delivery,index)=><button type="button" key={delivery.id}><strong>{index+1}</strong><span><b>{delivery.customer}</b><small>{delivery.address} · {delivery.district}</small></span><StatusBadge status={delivery.status}/></button>)}</div></div>:<EmptyState icon={MapPin} title="Nenhuma entrega no mapa" description="Cadastre uma entrega e confirme o endereço para visualizar sua localização." actionLabel="Ver entregas" onAction={()=>go("Entregas")}/>}</div>
}

function Deliveries({data,query,setQuery,remove}:{data:Delivery[];query:string;setQuery:(s:string)=>void;remove:(id:number)=>void}){const fees=data.reduce((s,d)=>s+d.deliveryFee,0);return <div className="content"><div className="list-finance"><div><span>Taxas desta lista</span><b>{money(fees)}</b></div><div><span>Já concluído</span><b>{money(data.filter(d=>d.status==="Entregue").reduce((s,d)=>s+d.deliveryFee,0))}</b></div><div><span>Valor dos pedidos</span><b>{money(data.reduce((s,d)=>s+d.amount,0))}</b></div></div><div className="toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente, telefone, endereço ou pedido"/></label><button><SlidersHorizontal/> Filtros</button><select><option>Todos os status</option><option>Aguardando</option><option>Em rota</option></select></div><div className="table-card"><div className="table-head"><b>{data.length} entregas</b><span>Atualizado agora</span></div><div className="delivery-table"><div className="tr th"><span>Pedido / Cliente</span><span>Endereço</span><span>Pedido / Taxa</span><span>Prioridade</span><span>Motoboy</span><span>Status</span><span/></div>{data.map(d=><div className="tr" key={d.id}><span><b>{d.order} · {d.customer}</b><small>{d.phone} · {d.time}</small></span><span><b>{d.district}</b><small>{d.address}</small></span><span><b>{money(d.amount)}</b><small className="fee-value">Taxa: {money(d.deliveryFee)}</small></span><span><Priority p={d.priority}/></span><span><b>{d.driver}</b></span><span><StatusBadge status={d.status}/></span><span className="row-actions"><button title="Visualizar"><Eye/></button><button title="Editar"><Pencil/></button><button title="Excluir" onClick={()=>remove(d.id)}><Trash2/></button></span></div>)}</div></div></div>}

function RoutePlanner({deliveries,notify,mapProvider}:{deliveries:Delivery[];notify:(s:string)=>void;mapProvider:MapTileProvider}){
  const [result,setResult]=useState<RouteResult|null>(null); const [loading,setLoading]=useState(false); const [returnToStart,setReturnToStart]=useState(true); const [expectedReturn,setExpectedReturn]=useState("—"); const selected=deliveries.filter(d=>d.status!=="Entregue"&&d.status!=="Problema").slice(0,5);
  async function calculate(){setLoading(true);try{const route=await calculateRoute([STORE_POINT,...selected.map(d=>({latitude:d.latitude,longitude:d.longitude}))],returnToStart);setResult(route);const returnMinutes=(13*60+30+Math.ceil(route.durationSeconds/60))%(24*60);setExpectedReturn(`${String(Math.floor(returnMinutes/60)).padStart(2,"0")}:${String(returnMinutes%60).padStart(2,"0")}`);notify(`Rota calculada gratuitamente por ${providerName(route.provider)}`)}catch(error){notify(error instanceof Error?error.message:"Não foi possível calcular a rota")}finally{setLoading(false)}}
  const minutes=result?Math.round(result.durationSeconds/60):0;
  return <div className="route-page"><div className="route-panel"><div className="route-config"><label>Ponto de saída<select><option>{loadStore().name||loadStore().address||"Defina a loja em Configurações"}</option><option>Usar minha localização atual</option></select></label><div className="inline"><label>Motoboy<select><option>Não atribuído</option></select></label><label>Saída<input type="time" defaultValue="13:30"/></label></div><label className="check"><input type="checkbox" checked={returnToStart} onChange={event=>setReturnToStart(event.target.checked)}/> Retornar ao estabelecimento</label></div><div className="stop-title"><div><b>Paradas selecionadas</b><span>{selected.length} de 5</span></div><button>Selecionar entregas</button></div><div className="stops">{selected.map((d,i)=><div className="stop" key={d.id}><i>⋮⋮</i><strong>{result?i+1:"·"}</strong><div><b>{d.customer}</b><span>{d.district} · {d.address}</span><small>{d.order} · até {d.time}</small></div><Priority p={d.priority}/><button><X/></button></div>)}</div><div className="route-actions"><button className="primary wide" disabled={loading} onClick={calculate}><Route/> {loading?"Calculando em serviços gratuitos…":result?"Recalcular rota":"Calcular melhor rota"}</button>{result&&<small>Rota viária: {providerName(result.provider)} · fallback automático ativo</small>}</div></div><div className="route-map"><div className="route-summary"><div><span>Distância total</span><b>{result?(result.distanceMeters/1000).toLocaleString("pt-BR",{maximumFractionDigits:1})+" km":"—"}</b></div><div><span>Tempo estimado</span><b>{result?(minutes>=60?`${Math.floor(minutes/60)}h ${minutes%60}min`:`${minutes} min`):"—"}</b></div><div><span>Paradas</span><b>{result?selected.length:"—"}</b></div><div><span>Retorno previsto</span><b>{expectedReturn}</b></div>{result&&<button className="primary" onClick={()=>notify("Planejamento salvo")}>Salvar planejamento</button>}</div><FreeMap deliveries={result?selected:[]} mapProvider={mapProvider} route={result}/>{!result&&!loading&&<div className="map-empty"><Route/><b>A rota aparecerá aqui</b><span>OSRM, Valhalla e fallback local estão disponíveis sem cobrança.</span></div>}</div></div>
}

function providerName(provider:RouteResult["provider"]){return ({osrm:"OSRM",valhalla:"Valhalla",openrouteservice:"OpenRouteService",graphhopper:"GraphHopper",local:"cálculo local"} as const)[provider]}

function Drivers(){return <div className="content"><div className="section-head"><div><h2>Equipe de entrega</h2><p>Cadastre a sua equipe de entrega</p></div><button className="primary"><Plus/> Cadastrar motoboy</button></div><div className="driver-grid">{[].map((d,i)=><article key={d[1]}><div className="driver-top"><div className="driver-avatar">{d[0]}</div><div><b>{d[1]}</b><span>(71) 99{i+2}40-18{i}2</span></div><MoreHorizontal/></div><div className="vehicle"><Bike/><div><span>{d[2]}</span><b>{d[3]}</b></div></div><div className="driver-earnings"><span>Fez hoje</span><b>{d[5]}</b></div><div className="driver-foot"><StatusBadge status={i===0?"Em rota":i===1?"Pronta para sair":"Aguardando"}/><span>{d[4]}</span></div></article>)}</div></div>}

function Config({notify,mapProvider,setMapProvider}:{notify:(s:string)=>void;mapProvider:MapTileProvider;setMapProvider:(provider:MapTileProvider)=>void}){
  const init=loadStore();
  const [name,setName]=useState(init.name);const [phone,setPhone]=useState(init.phone);const [address,setAddress]=useState(init.address);const [saving,setSaving]=useState(false);
  const [geoInfo,setGeoInfo]=useState(init.address&&init.latitude?`Ponto de saida definido (${init.latitude.toFixed(4)}, ${init.longitude.toFixed(4)})`:"Informe o endereco da loja para posicionar o ponto de saida.");
  async function save(){setSaving(true);try{let lat=init.latitude,lng=init.longitude;if(address.trim()){const r=await geocode(address);if(r){lat=r.latitude;lng=r.longitude;setGeoInfo(`Localizado: ${r.displayName}`);}else{setGeoInfo("Endereco salvo, mas nao localizei no mapa. Detalhe rua, numero, bairro e cidade.");}}saveStore({name,phone,address,latitude:lat,longitude:lng});notify("Endereco da loja salvo.");}catch(e){setGeoInfo(e instanceof Error?e.message:"Falha ao localizar endereco.");}finally{setSaving(false);}}
  const integrations=[["OpenStreetMap / CARTO / OpenTopoMap","Mapas sem chave e sem cobranca"],["Nominatim + Photon","Busca e localizacao de enderecos"],["OSRM + Valhalla","Roteirizacao viaria gratuita"],["GPS do aparelho","Localizacao atual com permissao"],["OCR Tesseract","Leitura de comanda por foto, no aparelho"]];
  return <div className="content config"><section><h2>Dados do estabelecimento</h2><p>Endereco editavel usado como ponto de saida das rotas.</p><div className="form-grid"><label>Nome do estabelecimento<input value={name} onChange={e=>setName(e.target.value)} placeholder="House Burger 190"/></label><label>Telefone<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="(00) 00000-0000"/></label><label className="full">Endereco principal<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="Rua, numero, bairro, cidade - UF"/></label><label>Mapa gratuito<select value={mapProvider} onChange={event=>setMapProvider(event.target.value as MapTileProvider)}>{Object.entries(MAP_TILE_PROVIDERS).map(([id,provider])=><option key={id} value={id}>{provider.name}</option>)}</select></label></div><div className="locate" style={{marginBottom:"14px"}}><MapPin/><div><b>Ponto de saida</b><span>{geoInfo}</span></div></div><button className="primary" disabled={saving} onClick={save}>{saving?"Salvando...":"Salvar alteracoes"}</button></section><section><h2>APIs gratuitas</h2><p>Servicos ativados com fallback automatico.</p>{integrations.map(x=><div className="integration" key={x[0]}><div className="ok"><CheckCircle2/></div><div><b>{x[0]}</b><span>{x[1]}</span></div><span className="free-badge">GRATIS</span></div>)}</section></div>;
}

function NewDelivery({close,save,prefill}:{close:()=>void;save:(e:React.FormEvent<HTMLFormElement>)=>void;prefill?:Record<string,string>|null}){const pf=(k:string)=>prefill?.[k]||"";
  const form=useRef<HTMLFormElement|null>(null); const [location,setLocation]=useState<GeoPoint|null>(null); const [locationText,setLocationText]=useState("Use a busca gratuita ou o GPS do aparelho."); const [locating,setLocating]=useState(false);
  async function locateAddress(){if(!form.current)return;const data=new FormData(form.current);const address=[data.get("address"),data.get("district"),data.get("city"),"BA","Brasil"].filter(Boolean).join(", ");setLocating(true);setLocationText("Buscando endereço…");try{const result=await geocode(address);if(!result){setLocationText("Endereço não encontrado. Complete rua, número e bairro.");return}setLocation(result);setLocationText(`${result.displayName} · ${result.provider||"serviço gratuito"}`)}catch(error){setLocationText(error instanceof Error?error.message:"Busca indisponível")}finally{setLocating(false)}}
  async function useGps(){setLocating(true);setLocationText("Obtendo localização do aparelho…");try{const point=await currentPosition();setLocation(point);const address=await reverseGeocode(point);setLocationText(address?.displayName||"Localização GPS encontrada")}catch(error){setLocationText(error instanceof Error?error.message:"GPS indisponível")}finally{setLocating(false)}}
  return <div className="overlay"><div className="modal large"><div className="modal-head"><div><h2>Nova entrega</h2><p>Cadastre o pedido e localize gratuitamente no mapa.</p></div><button onClick={close}><X/></button></div><form ref={form} onSubmit={save}><input type="hidden" name="latitude" value={location?.latitude||""}/><input type="hidden" name="longitude" value={location?.longitude||""}/><div className="form-grid"><label>Número do pedido<input name="order" defaultValue={pf("order")||"#1853"} required/></label><label>Nome do cliente<input name="customer" defaultValue={pf("customer")} placeholder="Nome completo" required/></label><label>Telefone<input name="phone" defaultValue={pf("phone")} placeholder="(71) 99999-9999" required/></label><label>CEP<input name="postalCode" defaultValue={pf("postalCode")} placeholder="00000-000"/></label><label className="full">Rua e número<input name="address" defaultValue={pf("address")} placeholder="Ex.: Rua das Acácias, 120" required/></label><label>Bairro<input name="district" defaultValue={pf("district")} placeholder="Bairro" required/></label><label>Cidade<input name="city" defaultValue={pf("city")||"Teixeira de Freitas"}/></label><label>Valor do pedido<input name="amount" type="number" step="0.01" defaultValue={pf("amount")} placeholder="R$ 0,00" required/></label><label>Valor da entrega<input name="deliveryFee" type="number" step="0.01" defaultValue={pf("deliveryFee")} placeholder="R$ 0,00" required/><small className="field-help">Taxa que será somada ao faturamento das entregas</small></label><label>Forma de pagamento<select name="payment" defaultValue={pf("payment")||"Pix"}><option>Pix</option><option>Dinheiro</option><option>Cartão</option><option>Pago</option></select></label><label className="full">Observações<textarea placeholder="Ponto de referência, instruções ou troco"/></label></div><div className="locate"><MapPin/><div><b>Localização do endereço</b><span>{locationText}</span></div><div className="locate-actions"><button type="button" disabled={locating} onClick={locateAddress}>Buscar endereço</button><button type="button" disabled={locating} onClick={useGps}><Navigation size={14}/> Usar GPS</button></div></div><div className="modal-actions"><button type="button" onClick={close}>Cancelar</button><button className="primary" type="submit">Confirmar e cadastrar entrega</button></div></form></div></div>
}

function OCR({close,done}:{close:()=>void;done:(fields:Record<string,string>)=>void}){
  const [preview,setPreview]=useState<string>("");
  const [file,setFile]=useState<File|null>(null);
  const [progress,setProgress]=useState(0);
  const [reading,setReading]=useState(false);
  const inputRef=useRef<HTMLInputElement|null>(null);
  function pick(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setFile(f);setPreview(URL.createObjectURL(f));setProgress(0);}
  async function process(){if(!file)return;setReading(true);setProgress(1);try{const {readReceipt}=await import("../src/services/ocrService");const res=await readReceipt(file,(n)=>setProgress(Math.max(1,n)));done(parseComanda(res.rawText));}catch(err){console.error(err);alert("Nao consegui ler a imagem. Tente uma foto mais nitida, reta e bem iluminada.");}finally{setReading(false);}}
  return <div className="overlay"><div className="modal ocr-modal"><div className="modal-head"><div><h2>Ler comanda</h2><p>A imagem e lida somente neste aparelho (OCR gratuito).</p></div><button onClick={close}><X/></button></div><input ref={inputRef} type="file" accept="image/*" capture="environment" hidden onChange={pick}/>{!preview?<div className="dropzone"><div><ScanLine/></div><b>Fotografe ou escolha uma comanda</b><span>Use uma foto nitida, bem iluminada e sem inclinacao.</span><button className="primary" onClick={()=>inputRef.current?.click()}><Camera/> Tirar foto</button><button onClick={()=>inputRef.current?.click()}><Upload/> Galeria</button></div>:<><div className="receipt-preview"><img src={preview} alt="comanda" style={{maxHeight:"280px",maxWidth:"100%",objectFit:"contain"}}/><button title="Trocar foto" onClick={()=>inputRef.current?.click()}><RotateCw/></button></div>{(reading||progress>0)?<div className="progress"><div><span style={{width:progress+"%"}}/></div><b>Lendo comanda... {progress}%</b><small>Reconhecendo texto em portugues</small></div>:<button className="primary wide" onClick={process}><ScanLine/> Iniciar leitura</button>}</>}</div></div>;
}

function StatusBadge({status}:{status:Status}){return <span className={"status "+status.toLowerCase().replaceAll(" ","-")}>{status}</span>}
function Priority({p}:{p:Delivery["priority"]}){return <span className={"priority "+p.toLowerCase()}>{p}</span>}
function parseComanda(text:string):Record<string,string>{
  const t=(text||"").replace(/\r/g,"");
  const g=(re:RegExp)=>{const m=t.match(re);return m?String(m[1]||"").trim().replace(/\s+/g," "):"";};
  const num=(v:string)=>{const m=v.replace(/[^\d.,]/g,"").replace(/\.(?=\d{3}(\D|$))/g,"").replace(",",".");const n=parseFloat(m);return isFinite(n)?String(n):"";};
  const out:Record<string,string>={};
  out.order=g(/(?:pedido|comanda)\s*#?\s*([0-9]{2,})/i);
  out.customer=g(/cliente[:\-\s]+([^\n]+)/i);
  out.phone=g(/(?:tel|telefone|fone|whats)[:\-\s]+([^\n]+)/i)||g(/(\(?\d{2}\)?\s?9?\d{4}[-\s]?\d{4})/);
  out.address=g(/endere[c\u00e7]o[:\-\s]+([^\n]+)/i);
  const comp=g(/comp(?:lemento)?[:\-\s]+([^\n]+)/i);if(comp)out.address=(out.address?out.address+", ":"")+comp;
  out.district=g(/bairro[:\-\s]+([^\n]+)/i);
  out.city=g(/cidade[:\-\s]+([^\n]+)/i);
  out.postalCode=g(/cep[:\-\s]*([0-9]{5}-?[0-9]{3})/i);
  const taxa=g(/taxa de entrega[:\-\s]*R?\$?\s*([\d.,]+)/i)||g(/taxa de servi[c\u00e7]o[^\n]*?R?\$?\s*([\d.,]+)/i);
  out.deliveryFee=taxa?num(taxa):"";
  const total=g(/valor total do pedido[:\-\s]*R?\$?\s*([\d.,]+)/i)||g(/valor pago[:\-\s]*R?\$?\s*([\d.,]+)/i)||g(/\btotal[:\-\s]*R?\$?\s*([\d.,]+)/i);
  out.amount=total?num(total):"";
  if(/pix/i.test(t))out.payment="Pix";else if(/cart[a\u00e3]o|cr[e\u00e9]dito|d[e\u00e9]bito/i.test(t))out.payment="Cartão";else if(/dinheiro/i.test(t))out.payment="Dinheiro";else if(/pago|online|ifood/i.test(t))out.payment="Pago";
  Object.keys(out).forEach(k=>{if(!out[k])delete out[k];});
  return out;
}
const money=(v:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(v);
